AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rss-rfd-lambda

  Sample SAM Template for rss-lambda
  
Globals:
  Function:
    Timeout: 3

Resources:
  RssRFDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: rss-rfd/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        MyScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

Outputs:
  RssRFDFunction:
    Description: "Rss RFD Lambda Function ARN"
    Value: !GetAtt RssRFDFunction.Arn
  RssRFDFunctionIamRole:
    Description: "Implicit IAM Role created for Rss RFD function"
    Value: !GetAtt RssRFDFunctionRole.Arn
